name: Continuous Integration
on:
  push:
    tags:
      - v1.*
      - v2.*
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: [graalvm@20.0.0, adopt@1.11]
    name: Test ${{ matrix.os }} -- ${{ matrix.jdk }}
    env:
      HYDRA_LICENSE: ${{ secrets.HYDRA_LICENSE }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.jdk }}
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Set up environment
        run: |
          curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help
          yarn --help
          java -version
          [[ $HYDRA_LICENSE == floating-key=* ]] && mkdir -p $HOME/.triplequote && echo "$HYDRA_LICENSE" > "$HOME/.triplequote/hydra.license" || echo "Hydra license file was not created"
        shell: bash
      - name: Check formatting
        if: matrix.os != 'windows-latest'
        run: |
          ./bin/sbt-ci.sh \
              "scalafmtCheckAll" \
        shell: bash
      - name: Compile and test main projects
        run: |
          ./bin/sbt-ci.sh \
              "frontend/test:compile" \
              "sbtBloop013/compile" \
              "sbtBloop10/compile" \
              "millBloop/compile" \
              "mavenBloop/compile" \
              "backend/test" \
              "docs/compile" \
              "jsBridge06/publishLocal" \
              "jsBridge10/publishLocal" \
              "frontend/testOnly bloop.ScalaVersionsSpec" \
              "frontend/testOnly -bloop.ScalaVersionsSpec" \
              "jsBridge06/test" \
              "jsBridge10/test" \
              "frontend/runMain bloop.util.CommandsDocGenerator --test" \
              "frontend/runMain bloop.util.CommandsDocGenerator --out ../docs/cli/reference.md"
        shell: bash
      - name: Check docs are up-to-date
        run: |
          ./bin/check-good-practices.sh
        shell: bash
      - name: Run launcher tests
        if: matrix.jdk == 'graalvm@20.0.0'
        run: |
          echo $JAVA_HOME
          which gu && gu install native-image
          ./bin/sbt-ci.sh "install" "launcher/test"
        shell: bash
      - name: Run build tool + native tests
        if: matrix.jdk == 'graalvm@20.0.0' && matrix.os != 'windows-latest'
        run: |
          ./bin/sbt-ci.sh \
              "millBloop/compile" \
              "mavenBloop/compile" \
              "gradleBloop211/compile" \
              "gradleBloop212/compile" \
              "gradleBloop212/test" \
              "sbtBloop10Shaded/publishLocal" \
              "sbtBloop10/scripted" \
              "benchmarks/jmh:run .*HotBloopBenchmark.* -wi 0 -i 1 -f1 -t1 -p project=with-tests -p projectName=with-tests"
        shell: bash

  publish-binaries:
    name: Publish binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        jdk: [graalvm@20.0.0]
        include:
          - os: ubuntu-latest
            artifact: bloop-linux
          - os: macos-latest
            artifact: bloop-macos
    env:
      CI: true
      SKIP_TEST_RESOURCES_GENERATION: true
      GITHUB_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
      BLOOPOID_GITHUB_TOKEN: ${{ secrets.BLOOPOID_GITHUB_TOKEN }}
      ARTIFACT_NAME: ${{ matrix.artifact }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.jdk }}
      - name: Publish GraalVM Native artifacts
        run: |
          echo $JAVA_HOME
          which gu
          gu install native-image
          ./bin/sbt-ci.sh "bloopgun/graalvm-native-image:packageBin"
          mkdir bloop-artifacts
          cp bloopgun/target/graalvm-native-image/bloopgun-core bloop-artifacts/$ARTIFACT_NAME
        shell: bash
      - uses: actions/upload-artifact@master
        with:
          name: bloop-artifacts
          path: bloop-artifacts/${{ matrix.artifact }}
      

  release:
    name: Publish on ${{ matrix.os }}
    needs: publish-binaries
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        jdk: [graalvm@20.0.0]
    env:
      CI: true
      SKIP_TEST_RESOURCES_GENERATION: true
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_PASS: ${{ secrets.BINTRAY_PASSWORD }}
      PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSWORD }}
      PGP_PUBLIC_KEY: ${{ secrets.PGP_PUBLIC_KEY }}
      PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
      GITHUB_DEPLOY_KEY: ${{ secrets.GITHUB_DEPLOY_KEY }}
      BLOOPOID_GITHUB_TOKEN: ${{ secrets.BLOOPOID_GITHUB_TOKEN }}
      BLOOPOID_SSH_PUBLIC_KEY: ${{ secrets.BLOOPOID_SSH_PUBLIC_KEY }}
      BLOOPOID_SSH_PRIVATE_KEY: ${{ secrets.BLOOPOID_SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ matrix.jdk }}
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Download built GraalVM binaries
        uses: actions/download-artifact@v1
        with:
          name: bloop-artifacts
      - name: Set up environment
        run: |
          curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help
          yarn --help
        shell: bash
      - name: Publish docs and binaries to Maven Central/Bintray
        run: |
          yarn install
          touch ~/.profile
          mkdir "$HOME/.ssh"
          mkdir "$HOME/.sbt"
          mkdir "$HOME/.sbt/gpg"
          git config --global user.name "Bloopoid"
          git config --global user.email "bloop@vican.me"
          git config --global push.default simple
          echo "$PGP_PUBLIC_KEY" > "$HOME/.sbt/gpg/pubring.asc"
          echo "$PGP_PRIVATE_KEY" > "$HOME/.sbt/gpg/secring.asc"
          ls -l bloop-artifacts
          mkdir -p frontend/target
          mv bloop-artifacts frontend/target/graalvm-binaries
          ./bin/sbt-ci-publish.sh "releaseBloop" "docs/docusaurusPublishGhpages"
        shell: bash
      - name: Cut GitHub release and update installers on ${{ matrix.os }}
        run: |
          . bin/ci-setup-bloopoid-keys.sh
          export GITHUB_TOKEN="$BLOOPOID_GITHUB_TOKEN"
          ./bin/sbt-ci-release.sh "frontend/updateHomebrewFormula" "frontend/updateScoopFormula" "frontend/githubRelease"
